-- Run this in Supabase SQL editor.
-- Note: policies below are open for anon usage for quick prototyping.
-- Tighten RLS before production deployment.

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  chapter text not null,
  finnish text not null,
  english text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists words_chapter_finnish_english_unique
  on public.words (chapter, finnish, english);

create table if not exists public.progress_sessions (
  id bigint generated by default as identity primary key,
  user_name text not null,
  chapter text not null default 'Mixed',
  mode text not null,
  timed boolean not null default false,
  round_result text not null default 'completed',
  words_in_round integer not null default 0 check (words_in_round >= 0),
  correct_count integer not null default 0 check (correct_count >= 0),
  attempts_count integer not null default 0 check (attempts_count >= 0),
  source text not null default 'local',
  completed_at timestamptz not null default now()
);

create table if not exists public.progress_word_stats (
  id bigint generated by default as identity primary key,
  progress_session_id bigint not null references public.progress_sessions(id) on delete cascade,
  word_id bigint references public.words(id) on delete set null,
  chapter text not null default 'General',
  finnish text not null,
  english text not null,
  attempts integer not null default 0 check (attempts >= 0),
  correct integer not null default 0 check (correct >= 0)
);

create table if not exists public.user_stats (
  user_name text primary key,
  times_played integer not null default 0 check (times_played >= 0),
  correct_guesses integer not null default 0 check (correct_guesses >= 0),
  total_attempts integer not null default 0 check (total_attempts >= 0),
  updated_at timestamptz not null default now()
);

alter table public.words enable row level security;
alter table public.progress_sessions enable row level security;
alter table public.progress_word_stats enable row level security;
alter table public.user_stats enable row level security;

drop policy if exists words_select_anon on public.words;
drop policy if exists words_insert_anon on public.words;
drop policy if exists words_update_anon on public.words;

create policy words_select_anon on public.words
  for select to anon using (true);

create policy words_insert_anon on public.words
  for insert to anon with check (true);

create policy words_update_anon on public.words
  for update to anon using (true) with check (true);

drop policy if exists progress_sessions_select_anon on public.progress_sessions;
drop policy if exists progress_sessions_insert_anon on public.progress_sessions;

create policy progress_sessions_select_anon on public.progress_sessions
  for select to anon using (true);

create policy progress_sessions_insert_anon on public.progress_sessions
  for insert to anon with check (true);

drop policy if exists progress_word_stats_select_anon on public.progress_word_stats;
drop policy if exists progress_word_stats_insert_anon on public.progress_word_stats;

create policy progress_word_stats_select_anon on public.progress_word_stats
  for select to anon using (true);

create policy progress_word_stats_insert_anon on public.progress_word_stats
  for insert to anon with check (true);

drop policy if exists user_stats_select_anon on public.user_stats;
drop policy if exists user_stats_insert_anon on public.user_stats;
drop policy if exists user_stats_update_anon on public.user_stats;

create policy user_stats_select_anon on public.user_stats
  for select to anon using (true);

create policy user_stats_insert_anon on public.user_stats
  for insert to anon with check (true);

create policy user_stats_update_anon on public.user_stats
  for update to anon using (true) with check (true);
